# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Conda-MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: 3
    - name: Set up conda-env
      run: |
        conda install setuptools wheel cmake ninja numpy
        conda install -c cjs14 aiida-quantumespresso
        pip install scikit-build
    - name: Install package
      run: python3 -m pip install .[dev]
    - name: Test with pytest
      run: python3 -m pytest
